services:
  poliswag:
    build: .
    image: poliswag
    container_name: poliswag
    restart: unless-stopped
    init: true
    ports:
      - "8989:8989"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - /root/PoGoLeiria/public:/pogo-public
    env_file:
      - .env
    networks:
      - scanner
    logging:
      driver: json-file
      options:
        max-size: "10m"

networks:
  scanner:
    external: true
